import IconMail from "@/components/icons/IconMail";

export { default as IconLogo } from "./IconLogo";
export { default as IconEasy } from "./IconEasy";
export { default as IconGlobe } from "./IconGlobe";
export { default as IconSign } from "./IconSign";
export { default as IconSearch } from "./IconSearch";
export { default as IconSearchSmall } from "./IconSearchSmall";
export { default as IconMenuOff } from "./IconMenuOff";
export { default as IconMenuOn } from "./IconMenuOn";
export { default as IconArrowLeft } from "./IconArrowLeft";
export { default as IconArrowRight } from "./IconArrowRight";
export { default as IconButterfly } from "./IconButterfly";
export { default as IconFacebook } from "./IconFacebook";
export { default as IconInstagram } from "./IconInstagram";
export { default as IconLinkedIn } from "./IconLinkedIn";
export { default as IconMastodon } from "./IconMastodon";
export { default as IconWhatsApp } from "./IconWhatsApp";
export { default as IconYouTube } from "./IconYouTube";
export { default as IconXing } from "./IconXing";
export { default as IconPlay } from "./IconPlay";
export { default as IconPlus } from "./IconPlus";
export { default as IconTelephone } from "./IconTelephone";
export { default as IconMail } from "./IconMail";
export { default as IconFullLogo } from "./IconFullLogo";
export { default as IconFullLogoLight } from "./IconFullLogoLight";
export { default as IconHome } from "./IconHome";